#!/usr/bin/env python3
"""Render docs/valuation-evidence/SEED_45_INVESTIGATION.md from the research JSON.

The JSON files under research/valuation-evidence/ are the source of truth; the
Markdown matrix is generated so the two can never drift apart.

Usage:
  python3 scripts/render_seed_investigation.py          # rewrite the Markdown
  python3 scripts/render_seed_investigation.py --check  # exit 1 if out of date
"""
import argparse
import json
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESEARCH_DIR = REPO_ROOT / "research" / "valuation-evidence"
REGISTRY_PATH = RESEARCH_DIR / "registry" / "transactions.v1.json"
INVESTIGATION_PATH = RESEARCH_DIR / "investigations" / "seed-45.v1.json"
OUTPUT_PATH = REPO_ROOT / "docs" / "valuation-evidence" / "SEED_45_INVESTIGATION.md"


def money(amount, currency):
    if amount is None:
        return "—"
    return f"{currency} {amount:,}" if currency != "USD" else f"${amount:,}"


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(registry, investigation):
    txs = {t["transaction_id"]: t for t in registry["transactions"]}
    records = investigation["records"]
    seed_status = Counter()
    for r in records:
        statuses = {txs[t]["evidence_status"] for t in r["transaction_ids"]}
        best = next(s for s in ("VERIFIED", "REPORTED", "DISPUTED", "UNVERIFIED") if s in statuses)
        seed_status[best] += 1

    lines = [
        "# Seed-45 Investigation Matrix",
        "",
        "<!-- Generated by scripts/render_seed_investigation.py from research/valuation-evidence/. Do not edit by hand. -->",
        "",
        f"- **As of:** {investigation['as_of']}",
        f"- **Seed file:** `{investigation['seed_file']}` (unchanged by Sprint 1A)",
        f"- **Method:** {investigation['method']}",
        f"- **Registry:** `research/valuation-evidence/registry/transactions.v1.json` "
        f"({registry['transaction_count']} transactions, content hash `{registry['content_sha256'][:12]}…`)",
        "",
        "## Totals",
        "",
        "Transactions in the registry (one seed record can map to several transactions, for example repeat sales):",
        "",
        "| Evidence status | Transactions |",
        "| --- | --- |",
    ]
    for status in ("VERIFIED", "REPORTED", "DISPUTED", "UNVERIFIED"):
        lines.append(f"| {status} | {registry['status_counts'][status]} |")
    lines += ["", "| Analytical role | Transactions |", "| --- | --- |"]
    for role in ("CALIBRATION_CANDIDATE", "HOLDOUT_CANDIDATE", "REFERENCE_ONLY", "EXCLUDED", "UNDETERMINED"):
        lines.append(f"| {role} | {registry['role_counts'][role]} |")
    lines += ["", "Seed records by strongest evidence for any linked transaction:", "",
              "| Strongest evidence | Seed records |", "| --- | --- |"]
    for status in ("VERIFIED", "REPORTED", "DISPUTED", "UNVERIFIED"):
        lines.append(f"| {status} | {seed_status[status]} |")
    agreement = Counter(r["seed_agreement"] for r in records)
    lines += ["", "| Agreement between seed record and evidence | Seed records |", "| --- | --- |"]
    for key, n in sorted(agreement.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| {key} | {n} |")

    lines += ["", "## Matrix", "",
              "| # | Seed record | Transactions (status · price · date) | Agreement | Recommended role | Principal source |",
              "| --- | --- | --- | --- | --- | --- |"]
    for n, r in enumerate(records, 1):
        parts, source = [], "None located"
        for tid in r["transaction_ids"]:
            t = txs[tid]
            parts.append(f"{tid}: {t['evidence_status']} · {money(t['sale_price'], t['currency'])} "
                         f"({t['price_disclosure_status'].lower()}) · {t['sale_date'] or 'date unknown'}")
            if t["source_url"] and source == "None located":
                source = f"[{t['source_name']}]({t['source_url']})"
        seed = f"{r['seed_domain']} — ${r['seed_price']:,} ({r['seed_year']})"
        lines.append(f"| {n} | {cell(seed)} | {cell('<br>'.join(parts))} | {r['seed_agreement']} | "
                     f"{cell(r['recommended_role'])} | {cell(source)} |")

    lines += ["", "## Record notes", ""]
    for n, r in enumerate(records, 1):
        lines += [f"### {n}. {r['seed_domain']}", "",
                  f"- **Findings:** {r['findings']}",
                  f"- **Price/date conflicts:** {r['price_date_conflicts'] or 'None found.'}",
                  f"- **Transaction type:** {r['transaction_type_uncertainty']}",
                  f"- **Rights:** {r['rights_uncertainty']}",
                  f"- **Remaining work:** {r['remaining_work']}"]
        for tid in r["transaction_ids"]:
            t = txs[tid]
            lines.append(f"- **{tid}:** {t['notes']}")
            if t["verification_basis"]:
                lines.append(f"  - Verification basis: {t['verification_basis']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    investigation = json.loads(INVESTIGATION_PATH.read_text(encoding="utf-8"))
    text = render(registry, investigation)
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != text:
            print(f"FAIL: {OUTPUT_PATH.relative_to(REPO_ROOT)} is out of date; run scripts/render_seed_investigation.py")
            sys.exit(1)
        print("PASS: seed investigation matrix is up to date")
        return
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
